CREATE DATABASE PRAVEEN;
USE PRAVEEN;
CREATE  TABLE IF NOT EXISTS `BARBER_CUSTOMER` (
  `BARBER_CUSTOMER_ID` BIGINT AUTO_INCREMENT,
  `OWNER_ID` BIGINT,
  `NAME` VARCHAR(255),
  `PHONE` VARCHAR(255) NOT NULL,
  `ADDRESS` VARCHAR(255),
  `ACTIVE` VARCHAR(255) NOT NULL,
  `CREATED_DATE` DATETIME,
  `CREATED_BY` VARCHAR(255),
  `UPDATED_DATE` DATETIME,
  `UPDATED_BY` VARCHAR(255),
  PRIMARY KEY (`BARBER_CUSTOMER_ID`,`OWNER_ID`));
  
  CREATE  TABLE IF NOT EXISTS `BARBER_CUSTOMER_BILL` (
  `BARBER_CUSTOMER_BILL_ID` BIGINT AUTO_INCREMENT,
  `OWNER_ID` BIGINT,
  `BARBER_CUSTOMER_ID` BIGINT,
  `SERVICE` VARCHAR(255),
  `SERVICE_DESCRIPTION` VARCHAR(255),
  `TOTAL_AMOUNT` VARCHAR(255) NOT NULL,
  `ACTIVE` VARCHAR(255) NOT NULL,
  `CREATED_BY` VARCHAR(255),
  `CREATED_DATE` DATETIME,
  `UPDATED_BY` VARCHAR(255),
  `UPDATED_DATE` DATETIME,
   PRIMARY KEY (`BARBER_CUSTOMER_BILL_ID`,`OWNER_ID`),
   FOREIGN KEY (`BARBER_CUSTOMER_ID`) REFERENCES BARBER_CUSTOMER(`BARBER_CUSTOMER_ID`));
